name: PHP 7.4

on: push

jobs:
  php74:
    name: Check PHP 7.4
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.4
          args: --prefer-dist --ignore-platform-reqs

      - name: Check code styling
        run: composer ecs-check

      - name: Create keys
        run: ./bin/create_keys

      - name: Run unit and feature tests
        run: composer test
