name: PHP 8.2

on: push

jobs:
  php80:
    name: Check PHP 8.2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 8.2
          args: --prefer-dist --ignore-platform-reqs

      - name: Check code styling
        run: composer ecs-check

      - name: Create keys
        run: ./bin/create_keys

      - name: Run unit and feature tests
        run: composer test
